url: "https://GG1982.github.io" 
baseurl: "/premium-tutoring"      # <--- This is the magic key!
title: "GG Maths"

# Company Details
google_reviews_url: "https://www.google.com/search?q=ggmaths&oq=ggmaths&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg8MgoIAhAAGIAEGKIEMgoIAxAAGIAEGKIEMgoIBBAAGKIEGIkFMgYIBRBFGDwyBggGEEUYPTIGCAcQRRg80gEIMzEwMGowajeoAgCwAgA&sourceid=chrome&ie=UTF-8#lrd=0x48761923e87f01e1:0xb59e62c483b997c,1,,,,"