url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# Company Details
google_reviews_url: "https://www.google.com/search?q=ggmaths&oq=ggmaths&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg8MgoIAhAAGIAEGKIEMgoIAxAAGIAEGKIEMgoIBBAAGKIEGIkFMgYIBRBFGDwyBggGEEUYPTIGCAcQRRg80gEIMzEwMGowajeoAgCwAgA&sourceid=chrome&ie=UTF-8#lrd=0x48761923e87f01e1:0xb59e62c483b997c,1,,,,"